Support Kraken and Bracken db_params in database sheet
nf-core/taxprofiler pull request #237
Opened 2023-02-08 12:39 UTC by jfy133

Closes: https://github.com/nf-core/taxprofiler/issues/233

Basically requires bracken `db_params` entries for Bracken to be a semi-colon list, with the former entry going into Kraken and the latter into Bracken.

If bracken supplied and the db_params does not include `;`, it will fail.

I will upload the different samplesheets I tested on, by using `.dumps` before and after the `map` where I parse the db_params string in `profiling.nf`

Note this will fail on first CI run due to our current samplesheet being invalid

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/taxprofiler/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/taxprofiler _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-02-08 12:39 UTC, jfy133 commented
Files used for testing (bonly == bracken only, konly == krakenonly)

[database_split_bonly.csv](https://github.com/nf-core/taxprofiler/files/10685560/database_split_bonly.csv)
[database_split_both.csv](https://github.com/nf-core/taxprofiler/files/10685561/database_split_both.csv)
[database_split_broken.csv](https://github.com/nf-core/taxprofiler/files/10685562/database_split_broken.csv)
[database_split_konly.csv](https://github.com/nf-core/taxprofiler/files/10685564/database_split_konly.csv)
[database_split_none.csv](https://github.com/nf-core/taxprofiler/files/10685565/database_split_none.csv)

2023-02-08 15:11 UTC, Midnighter requested changes
Just a few minor things, otherwise looks good 🙂

2023-02-08 15:11 UTC, Midnighter commented on docs/usage.md
> +For Bracken, if you wish to supply amy parameters to either the Kraken or Bracken step you **must** have a _semi-colon_ `;` list as in `db_params`. This is to allow to specify the Kraken2 parameters
```suggestion
For Bracken, if you wish to supply any parameters to either the Kraken or Bracken step you **must** have a _semi-colon_ `;` list as in `db_params`. This is to allow to specify the Kraken2 parameters before, and Bracken parameters after the `;` as Bracken is a two step process. This is particularly important if you supply a Bracken database with a non-default read length parameter. If you do not have any parameters to specify, you can leave this as empty.
```

2023-02-08 15:11 UTC, Midnighter commented on subworkflows/local/profiling.nf
> +                                .dump(tag: "ch_input_for_kraken2_after")
Remove the dump?

```suggestion
```

2023-02-08 15:11 UTC, Midnighter commented on subworkflows/local/profiling.nf
> +            .dump(tag: "ch_input_for_bracken_b4")
```suggestion
```

2023-02-08 15:11 UTC, Midnighter commented on subworkflows/local/profiling.nf
> +            .dump(tag: "ch_input_for_bracken_after")
```suggestion
```

2023-02-09 07:01 UTC, jfy133 commented on conf/modules.config
> +        ext.args = { "${meta.db_params}" }
```suggestion
        errorStrategy = 'ignore'
        ext.args = { "${meta.db_params}" }
```

2023-02-09 07:03 UTC, jfy133 commented on conf/modules.config
> +        ext.args = { "${meta.db_params}" }
Good point, I thought it was the comebine bracken output step but I remember now it was also here I think, if there were no hits?

2023-02-09 09:15 UTC, Midnighter commented on conf/modules.config
> +        ext.args = { "${meta.db_params}" }
Yeah, either if all is unclassified or even if only one species was detected, it fails, too, I think.

2023-02-09 09:16 UTC, Midnighter approved these changes

2023-02-09 09:59 UTC, merged