Clone maps
nf-core/taxprofiler pull request #258
Opened 2023-03-07 14:02 UTC by Midnighter

I went through all cases in the pipeline where I could see a `Map` being modified. As far as I could see, we clone maps where necessary.

I tried to clean up the syntax a bit here and there but didn't do it in all places. So maybe that should be removed again.

I also marked with `FIXME` comments, where channel joins or groupings happen which are hot spots for further improvements in future. I can also take those out again.

2023-03-07 14:58 UTC, Midnighter commented on subworkflows/local/db_check.nf
> +            untar: db.name.endsWith(".tar.gz")
`db` is the parameter to the closure which in this case is a file path. The path has the attribute `.name`.

2023-03-07 15:01 UTC, sofstam commented on subworkflows/local/db_check.nf
> +            untar: db.name.endsWith(".tar.gz")
Ok, thank you.

2023-03-09 13:13 UTC, jfy133 commented on subworkflows/local/longread_preprocessing.nf
> +            .map { meta, reads -> [ meta + [single_end: 1], reads ] }
so this isn't additive, `single_end` will overwrite what it is in `meta`?

2023-03-09 13:14 UTC, jfy133 commented on subworkflows/local/longread_preprocessing.nf
> +        ch_processed_reads = FILTLONG ( ch_clipped_reads.map { meta, reads -> [meta, [], reads ] } ).reads
```suggestion
        ch_processed_reads = FILTLONG ( ch_clipped_reads.map { meta, reads -> [ meta, [], reads ] } ).reads
```

2023-03-09 13:17 UTC, jfy133 requested changes

2023-03-09 13:17 UTC, jfy133 commented on subworkflows/local/input_check.nf
> +    def meta = row.subMap(['sample', 'run_accession', 'instrument_platform'])
I think this is breaking the tests -> `sample` should be recorded as `id`

2023-03-09 13:40 UTC, jfy133 reviewed
After speaking in gather: the FIXMEs aren't necessary

2023-03-09 13:41 UTC, jfy133 commented on subworkflows/local/longread_preprocessing.nf
> +            .map { meta, reads -> [ meta + [single_end: 1], reads ] }
Explained it does in perosn :)

2023-03-11 19:04 UTC, jfy133 approved these changes

2023-03-11 20:39 UTC, merged