Update taxpasta
nf-core/taxprofiler pull request #355
Opened 2023-08-25 14:29 UTC by sofstam

This PR updates taxpasta module to 0.5.0

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/taxprofiler/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/taxprofiler _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-08-25 14:43 UTC, jfy133 requested changes
- [ ] Need changelog depedency table update
- [ ] Need to add support for the new flags (rank lineage, for example)

2023-08-25 14:51 UTC, sofstam commented
We already have support for:

```
    taxpasta_add_name                       = false
    taxpasta_add_rank                       = false
    taxpasta_add_lineage                    = false
    taxpasta_add_idlineage                  = false
```

Or do you mean something different?

2023-08-25 17:03 UTC, jfy133 commented
Sorry new flag (singular)

https://taxpasta.readthedocs.io/en/latest/quick_reference/standardise/

`--add-rank-lineage` as added in https://github.com/taxprofiler/taxpasta/pull/130

2023-08-26 06:55 UTC, jfy133 approved these changes

2023-08-26 06:55 UTC, jfy133 commented on CHANGELOG.md
> +- [#355](https://github.com/nf-core/taxprofiler/pull/345) Add support for TAXPASTA's `--add-rank-lineage` to output (❤️ to @MajoroMask for request, added by @Midnighter, @sofstam, @jfy133)
```suggestion
- [#355](https://github.com/nf-core/taxprofiler/pull/355) Add support for TAXPASTA's `--add-rank-lineage` to output (❤️ to @MajoroMask for request, added by @Midnighter, @sofstam, @jfy133)
```

2023-08-26 06:55 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "\nThe standard output format of taxpasta is a two-column table including the read counts and the integer taxonomic ID. The taxonomicl levels taxon's entire lineage w
```suggestion
                    "help_text": "\nThe standard output format of taxpasta is a two-column table including the read counts and the integer taxonomic ID. The taxonomic ranks categories of the taxon's entire lineage separated by semi-colons can be added as additional information to the output table. This complements `--taxpasta_add_lineage` by telling you which taxonomic rank level each entry in the lineage refers to.\n\nModifies tool parameter(s):\n- taxpasta: `--add-rank-lineage`\n",
```

2023-08-26 08:01 UTC, jfy133 commented on CHANGELOG.md
> +| taxpasta  | 0.2.3            | 0.5.0       |
```suggestion
| TAXPASTA  | 0.2.3            | 0.5.0       |
```

2023-08-26 08:01 UTC, merged