Add motus preplong for long reads profiling
nf-core/taxprofiler pull request #559
Opened 2024-12-12 11:55 UTC by LilyAnderssonLee

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/taxprofiler/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/taxprofiler _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core pipelines lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2025-03-11 13:54 UTC, LilyAnderssonLee commented
Can you also add the docs for this part to `usage.md`?

2025-03-13 08:42 UTC, jfy133 requested changes
-  Missing CHANGELOG

2025-03-13 08:42 UTC, jfy133 commented on docs/usage.md
> +mOTUs currently does not accept FASTA files as input, therefore no output will be produced for these input files. For long reads, the `motus prep_long` command is being executed first to split long r
```suggestion
mOTUs currently does not accept FASTA files as input, therefore no output will be produced for these input files. 
For long reads, the `motus prep_long` command will be being executed first to split long reads into shorter reads which can then be profiled with `motus profile` command.
```

2025-03-13 08:42 UTC, jfy133 commented on subworkflows/local/profiling.nf
> +        //ch_versions        = ch_versions.mix( MOTUS_PREPLONG.out.versions.first() )
```suggestion
        ch_versions        = ch_versions.mix( MOTUS_PREPLONG.out.versions.first() )
```

2025-03-13 08:42 UTC, jfy133 commented on conf/modules.config
> +        tag = {"${meta.db_name}|${meta.id}"}
It might bve safer to also use the `ext.prefix` here too

2025-03-13 08:42 UTC, jfy133 commented on subworkflows/local/profiling.nf
> +        MOTUS_PROFILE ( MOTUS_PREPLONG.out.out.mix(ch_input_for_motus_shortread.reads), ch_input_for_motus_longread.db.mix(ch_input_for_motus_shortread.db) )
You need to mix the two into one input channel beforehand, and use a multiMap to make sure the reads and the db channels are insync

2025-03-13 10:20 UTC, sofstam commented on conf/modules.config
> +        tag = {"${meta.db_name}|${meta.id}"}
Added [here](https://github.com/nf-core/taxprofiler/commit/36e26e09b86f4e94d9d68e305502f16849080dce) and I am resolving this.

2025-03-13 12:10 UTC, jfy133 commented on subworkflows/local/profiling.nf
> +        MOTUS_PROFILE ( MOTUS_PREPLONG.out.out.mix(ch_input_for_motus_shortread.reads), ch_input_for_motus_longread.db.mix(ch_input_for_motus_shortread.db) )
Yes @sofstam !

2025-03-13 13:19 UTC, jfy133 commented
Btw, now the database has downlaoded :roll_eyes: 

Shoudl we add additional pipeline level parameters for `ext.args` of prep_long?

```

2025-03-13 13:19 UTC, jfy133 commented
```

2025-03-13 13:19 UTC, jfy133 commented
Wow sorry about that, github freaked out

2025-03-24 12:47 UTC, sofstam commented
nf-core fix linting

2025-03-24 12:48 UTC, sofstam commented
@nf-core-bot fix linting

2025-03-24 13:04 UTC, sofstam commented
> Btw, now the database has downlaoded 🙄
> 
> Shoudl we add additional pipeline level parameters for `ext.args` of prep_long -> the split length and min lead length seems imporant t ome?
> 
> ```
> Usage: motus prep_long -i <long_read_file> -o <converted_file> [options]
> 
> Input options:
>    -i  FILE   long read file to convert, can be fasta(.gz) or fastq(.gz)
> Output options:
>    -o  FILE   converted file (gzipped), ready to be used by motus profile
>    -no_gz     save the output file without gzipping it
> Algorithm options:
>    -sl INT    splitting length for the long reads [300]
>    -ml INT    minimum read length, shorter are discarded [50]
>    -v  INT    verbosity level: 1=error, 2=warning, 3=message, 4+=debugging [3]
> ```

We have only done this for ganon. Not sure if we shall add those to pipeline level. I can add those if you think they are necessary.

2025-03-25 13:21 UTC, sofstam commented
> minimum read length, shorter are discarded

The default value in the schema shall be 0 or the default value from motus? 300 and 50 respectively?

2025-03-25 13:40 UTC, jfy133 commented
> > minimum read length, shorter are discarded
> 
> The default value in the schema shall be 0 or the default value from motus? 300 and 50 respectively?

Default from mOTUs1

2025-03-25 13:49 UTC, jfy133 reviewed
Last few things !

2025-03-25 13:49 UTC, jfy133 commented on nextflow_schema.json
> +                "run_sylph": {
Is that meant to be in this PR?

2025-03-25 13:49 UTC, jfy133 commented on nextflow_schema.json
> +                    "description": "Splitting length for the long reads.",
Please add a `help_text` describing in more detail what/why it is doing

2025-03-25 13:49 UTC, jfy133 commented on nextflow_schema.json
> +                    "description": "Minimum read length, shorter are discarded.",
Please add a `help_text` describing in more detail what/why it is doing

2025-03-25 13:49 UTC, jfy133 commented on nextflow_schema.json
> +                    "description": "Splitting length for the long reads.",
Also missing the `'modifies XYZ tool parameters'`

2025-03-25 13:49 UTC, jfy133 commented on nextflow_schema.json
> +                    "description": "Minimum read length, shorter are discarded.",
Also missing the `'modifies XYZ tool parameters'`

2025-03-25 13:49 UTC, jfy133 commented on subworkflows/local/profiling.nf
> +                            }
Has the langauge sderver autoformatting been run on this file? The indentation looks all weird

2025-03-25 13:53 UTC, sofstam commented on nextflow_schema.json
> +                "run_sylph": {
No! Not sure how this happened :/ Thank you for spotting this, I am updating the PR.

2025-03-25 14:05 UTC, sofstam commented on nextflow_schema.json
> +                    "description": "Splitting length for the long reads.",
Updated PR

2025-03-26 12:41 UTC, jfy133 commented
@nf-core-bot fix linting

2025-03-26 12:58 UTC, jfy133 approved these changes
Last few things now  (just docs phrasing).
Can ou confirm the tests run and MOTUS PREPLONG is executed and MOTUS itself recieves those files?

2025-03-26 12:58 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "Specify the splitting length for the long reads.mOTUs has a default value 300`.\n\n> Modifies tool parameter(s):\n- motus prep_long: `--sl`",
```suggestion
                    "help_text": "Specify the splitting length for the long reads into short reads compatible with short read alignment against the marker genes .mOTUs has a default value 300`.\n\n> Modifies tool parameter(s):\n- motus prep_long: `--sl`",
```

2025-03-26 12:58 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "Specify the minimu read length. Reads shorted than the defined value will be discarded.mOTUs has a default value 50`.\n\n> Modifies tool parameter(s):\n- motus prep_
```suggestion
                    "help_text": "Specify the minimum read length of 'synthetic' short reads. The reads post-splitting shorter than the defined value will be discarded. mOTUs has a default value 50`.\n\n> Modifies tool parameter(s):\n- motus prep_long: `--ml`",
```

2025-03-26 12:58 UTC, jfy133 commented on nextflow_schema.json
> +                    "help_text": "This flag will generate the directory `results/analysis_read_reads` that contains the reads from the last preprocessing (QC, host removal, run merging etc.) step of
```suggestion
                    "help_text": "This flag will generate the directory `results/analysis_ready_reads` that contains the reads from the last preprocessing (QC, host removal, run merging etc.) step of the pipeline run. \n\nThis can be useful if you wish to re-use the final cleaned-up and prepared reads - the data actually used for the actual classification/profiling steps of the pipeline - for other analyses or purposes (e.g., to reduce redundant preprocessing between different pipelines, e.g. [nf-core/mag](https://nf-co.re/mag)).\n\nIn most cases this will be preferred over similar parameters e.g. ` --save_preprocessed_reads` or ` --save_complexityfiltered_reads`, unless you wish to explore in more detail the output of each specific preprocessing step independently.\n\nNote if you do no preprocessing of any kind, nothing will be present in this directory. "
```

2025-03-26 14:26 UTC, sofstam commented
@jfy133 Output from mOTUs

<img width="611" alt="Screenshot 2025-03-26 at 15 24 43" src="https://github.com/user-attachments/assets/4de5cad3-9ead-4a32-aee8-e953d2c6e7e2" />

2025-03-26 14:56 UTC, sofstam commented
@nf-core-bot fix linting

2025-03-26 15:23 UTC, jfy133 reviewed
@sofstam it looks like the output dir has extra files but aren't documented in `output.md` is that correct?

2025-03-26 15:33 UTC, sofstam commented
> @sofstam it looks like the output dir has extra files but aren't documented in `output.md` is that correct?

You are right! I added this now.

2025-03-26 18:15 UTC, jfy133 commented
I think you may have forgotten to push...

But before you do - I think the publishing of the synthetic long-reads should be opt in... I don't think most people will want them in most cases... what do you think?

2025-03-27 09:43 UTC, sofstam commented
> I think you may have forgotten to push...
> 
> But before you do - I think the publishing of the synthetic long-reads should be opt in... I don't think most people will want them in most cases... what do you think?

I pushed now. Good point, probably not. I can update to have it optional.

2025-03-27 10:05 UTC, sofstam commented
@nf-core-bot fix linting

2025-03-31 09:04 UTC, jfy133 reviewed
Last comment otherwise good to go @sofstam !

2025-03-31 09:04 UTC, jfy133 commented on conf/modules.config
> +            enabled: params.motus_save_long_reads
Maybe should be 'save cutup' long reads? It's not the actual long reads that are being saved right?

2025-03-31 09:04 UTC, jfy133 commented on docs/output.md
> +    - `<sample_id>.prep_long.gz`: Output file where long reads are converted into shorter reads.
```suggestion
    - `<sample_id>.prep_long.gz`: Output file of long reads that have cut up into into shorter reads.
```

2025-03-31 09:07 UTC, sofstam commented on conf/modules.config
> +            enabled: params.motus_save_long_reads
Hmm, true. Maybe `save_split_long_reads`?

2025-03-31 10:56 UTC, merged